### ISSUE TITLE
Extension for OpenCart-3.x not showing up

### ISSUE THREAD

**Issue by ruxxzebre** [upcecconnect/OpenCart-2.x-3.x#1]
Extension for OpenCart-3.x not showing up in Modificators -> Payments tab, so it's not possible to activate it.
Расширение для OpenCart третьей версии не высвечиваеться в расширениях, а значит его невозможно активировать или настроить.

**Comment by upcecconnect** [comment]
Спасибо за ваш отзыв. Исправили. Разархивируйте и устанавливайте ecc.ocmod.zip.

**Comment by ruxxzebre** [comment]
UPD: Пытался поправить строки, и если не ошибаюсь то модификация действительно появляеться в списке, вот только локализация не загружается, а починить так и не вышло. То есть условно я вижу heading_title вместо названия.
Были подозрения на то, что на сайте стояла украинская локализация "uk-ua", но даже при смене, ситуация не изменилась.
